#! /usr/bin/env bash

# Options.
DATADIR="/znc-data"
BITLBEEDATADIR="/bitlbee-data"

# Build modules from source.
if [ -d "${DATADIR}/modules" ]; then
  # Store current directory.
  cwd="$(pwd)"

  # Find module sources.
  modules=$(find "${DATADIR}/modules" -name "*.cpp")

  # Build modules.
  for module in $modules; do
    cd "$(dirname "$module")"
    znc-buildmod "$module"
  done

  # Go back to original directory.
  cd "$cwd"
fi

# Create default config if it doesn't exist
if [ ! -f "${DATADIR}/configs/znc.conf" ]; then
  mkdir -p "${DATADIR}/configs"
  cp /src/znc.conf.default "${DATADIR}/configs/znc.conf"
fi

# start bitlbee in background forking mode
bitlbee -F -i 127.0.0.1 -p 6668 -d $BITLBEEDATADIR
# Start ZNC.
exec znc --foreground --datadir="$DATADIR" $@
